/*
  Script: 00_create_sn_guias.sql
  Modulo: Guias (Despachos)
  Motor : Firebird 2.5

  Nota:
  - El ID de cada tabla se toma desde codigo PHP (MAX + 1).
  - El CONSECUTIVO de guia se calcula por PREFIJO (MAX + 1).
  - No se usan generators ni triggers para numeracion.
 */

/* ======================
   TABLA: SN_GUIAS
   ====================== */
CREATE TABLE SN_GUIAS (
    ID              INTEGER NOT NULL,
    FECHA_CREACION  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_EDICION   TIMESTAMP,
    USUARIO_CREA    VARCHAR(50) NOT NULL,
    USUARIO_EDITA   VARCHAR(50),
    PREFIJO         CHAR(2) NOT NULL,
    CONSECUTIVO     INTEGER NOT NULL,
    FECHA_GUIA      TIMESTAMP NOT NULL,
    ID_CONDUCTOR    INTEGER,
    ID_VEHICULO     INTEGER,
    ESTADO_ACTUAL   VARCHAR(20) DEFAULT 'EN_ALISTAMIENTO' NOT NULL
);

ALTER TABLE SN_GUIAS ADD CONSTRAINT PK_SN_GUIAS PRIMARY KEY (ID);
ALTER TABLE SN_GUIAS ADD CONSTRAINT UQ_SN_GUIAS_PREF_CONS UNIQUE (PREFIJO, CONSECUTIVO);
ALTER TABLE SN_GUIAS ADD CONSTRAINT FK_SN_GUIAS_CONDUCTOR FOREIGN KEY (ID_CONDUCTOR) REFERENCES TERCEROS (TERID);
ALTER TABLE SN_GUIAS ADD CONSTRAINT FK_SN_GUIAS_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO (VEHICULOID);

CREATE INDEX IDX_SN_GUIAS_FECHA_GUIA ON SN_GUIAS (FECHA_GUIA);
CREATE INDEX IDX_SN_GUIAS_ESTADO ON SN_GUIAS (ESTADO_ACTUAL);

/* ======================
   TABLA: SN_GUIAS_ESTADOS
   ====================== */
CREATE TABLE SN_GUIAS_ESTADOS (
    ID                INTEGER NOT NULL,
    ID_GUIA           INTEGER NOT NULL,
    ESTADO            VARCHAR(20) NOT NULL,
    FECHA_HORA_ESTADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO           VARCHAR(50) NOT NULL,
    OBSERVACION       VARCHAR(200)
);

ALTER TABLE SN_GUIAS_ESTADOS ADD CONSTRAINT PK_SN_GUIAS_ESTADOS PRIMARY KEY (ID);
ALTER TABLE SN_GUIAS_ESTADOS ADD CONSTRAINT FK_SN_GUIAS_EST_GUIA FOREIGN KEY (ID_GUIA) REFERENCES SN_GUIAS (ID) ON DELETE CASCADE;

CREATE INDEX IDX_SN_GUIAS_EST_GUIA_FECHA ON SN_GUIAS_ESTADOS (ID_GUIA, FECHA_HORA_ESTADO);

/* ======================
   TABLA: SN_GUIAS_DETALLE
   ====================== */
CREATE TABLE SN_GUIAS_DETALLE (
    ID             INTEGER NOT NULL,
    ID_GUIA        INTEGER NOT NULL,
    KARDEX_ID      INTEGER NOT NULL,
    FECHA_AGREGADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO_AGREGA VARCHAR(50) NOT NULL,
    PESO           NUMERIC(18,3) DEFAULT 0,
    VALOR_BASE     NUMERIC(18,2) DEFAULT 0
);

ALTER TABLE SN_GUIAS_DETALLE ADD CONSTRAINT PK_SN_GUIAS_DETALLE PRIMARY KEY (ID);
ALTER TABLE SN_GUIAS_DETALLE ADD CONSTRAINT FK_SN_GUIAS_DET_GUIA FOREIGN KEY (ID_GUIA) REFERENCES SN_GUIAS (ID) ON DELETE CASCADE;
ALTER TABLE SN_GUIAS_DETALLE ADD CONSTRAINT FK_SN_GUIAS_DET_KDX FOREIGN KEY (KARDEX_ID) REFERENCES KARDEX (KARDEXID);
ALTER TABLE SN_GUIAS_DETALLE ADD CONSTRAINT UQ_SN_GUIAS_DET_GUIA_K UNIQUE (ID_GUIA, KARDEX_ID);
ALTER TABLE SN_GUIAS_DETALLE ADD CONSTRAINT UQ_SN_GUIAS_DET_KARDEX UNIQUE (KARDEX_ID);

CREATE INDEX IDX_SN_GUIAS_DET_GUIA ON SN_GUIAS_DETALLE (ID_GUIA);

/* ======================
   TABLA: SN_GUIAS_ESTADOS_CFG
   ====================== */
CREATE TABLE SN_GUIAS_ESTADOS_CFG (
    ID              INTEGER NOT NULL,
    CODIGO          VARCHAR(30) NOT NULL,
    NOMBRE          VARCHAR(60) NOT NULL,
    ACTIVO          CHAR(1) DEFAULT 'S' NOT NULL,
    ORDEN_VISUAL    INTEGER DEFAULT 0,
    FECHA_CREACION  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_EDICION   TIMESTAMP,
    USUARIO_EDITA   VARCHAR(25)
);

ALTER TABLE SN_GUIAS_ESTADOS_CFG ADD CONSTRAINT PK_SN_GUIAS_ESTADOS_CFG PRIMARY KEY (ID);
ALTER TABLE SN_GUIAS_ESTADOS_CFG ADD CONSTRAINT UQ_SN_GUIAS_ESTADOS_CFG_COD UNIQUE (CODIGO);
ALTER TABLE SN_GUIAS_ESTADOS_CFG ADD CONSTRAINT CK_SN_GUIAS_ESTADOS_CFG_ACTIVO CHECK (ACTIVO IN ('S', 'N'));

CREATE INDEX IDX_SN_GUIAS_ESTADOS_CFG_ORD ON SN_GUIAS_ESTADOS_CFG (ORDEN_VISUAL);

INSERT INTO SN_GUIAS_ESTADOS_CFG (ID, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL, FECHA_CREACION)
VALUES (1, 'EN_ALISTAMIENTO', 'EN ALISTAMIENTO', 'S', 10, CURRENT_TIMESTAMP);

INSERT INTO SN_GUIAS_ESTADOS_CFG (ID, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL, FECHA_CREACION)
VALUES (2, 'EN_RUTA', 'EN RUTA', 'S', 20, CURRENT_TIMESTAMP);

INSERT INTO SN_GUIAS_ESTADOS_CFG (ID, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL, FECHA_CREACION)
VALUES (3, 'ENTREGADO', 'ENTREGADO', 'S', 30, CURRENT_TIMESTAMP);
