/*
  Script: 01_alter_kardex.sql
  Modulo: Guias (Despachos)
  Motor : Firebird 2.5
*/

ALTER TABLE KARDEX ADD SN_GUIA_ID INTEGER;

ALTER TABLE KARDEX
  ADD CONSTRAINT FK_KARDEX_SN_GUIA
  FOREIGN KEY (SN_GUIA_ID)
  REFERENCES SN_GUIAS (ID);

CREATE INDEX IDX_KARDEX_SN_GUIA_ID ON KARDEX (SN_GUIA_ID);
