/*
  Script: 02_create_permisos_menu.sql
  Modulo: Permisos de menu
  Motor : Firebird 2.5
  Base  : INVENTARIOS.GDB

  Nota:
  - Esta tabla guarda permisos por usuario y menu.
  - Si un usuario no tiene registros en esta tabla, el sistema lo toma como acceso total por defecto.
*/

CREATE TABLE SN_MENU_PERMISOS (
    ID              INTEGER NOT NULL,
    USUARIO         VARCHAR(25) NOT NULL,
    MENU_ID         VARCHAR(60) NOT NULL,
    PERMITIDO       CHAR(1) NOT NULL,
    FECHA_CREACION  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_EDICION   TIMESTAMP,
    USUARIO_EDITA   VARCHAR(25)
);

ALTER TABLE SN_MENU_PERMISOS ADD CONSTRAINT PK_SN_MENU_PERMISOS PRIMARY KEY (ID);
ALTER TABLE SN_MENU_PERMISOS ADD CONSTRAINT UQ_SN_MENU_PERMISOS_USR_MENU UNIQUE (USUARIO, MENU_ID);
ALTER TABLE SN_MENU_PERMISOS ADD CONSTRAINT CK_SN_MENU_PERMISOS_FLAG CHECK (PERMITIDO IN ('S', 'N'));

CREATE INDEX IDX_SN_MENU_PERMISOS_USUARIO ON SN_MENU_PERMISOS (USUARIO);
CREATE INDEX IDX_SN_MENU_PERMISOS_MENU_ID ON SN_MENU_PERMISOS (MENU_ID);
