/*
  Script: 03_create_despachos_conductor.sql
  Modulo: Despachos conductor
  Motor : Firebird 2.5
  Base  : CMDISTRI17-YYYY.GDB

  Nota:
  - IDs gestionados por codigo (MAX + 1), sin generators ni triggers.
  - Estado por remision para operacion de conductores.
*/

CREATE TABLE SN_GUIAS_DETALLE_ESTADO (
    ID              INTEGER NOT NULL,
    ID_GUIA         INTEGER NOT NULL,
    KARDEX_ID       INTEGER NOT NULL,
    ESTADO_ENTREGA  VARCHAR(20) NOT NULL,
    OBSERVACION     VARCHAR(300),
    FECHA_ESTADO    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO         VARCHAR(50) NOT NULL
);

ALTER TABLE SN_GUIAS_DETALLE_ESTADO ADD CONSTRAINT PK_SN_GUIAS_DET_EST PRIMARY KEY (ID);
ALTER TABLE SN_GUIAS_DETALLE_ESTADO ADD CONSTRAINT UQ_SN_GUIAS_DET_EST UNIQUE (ID_GUIA, KARDEX_ID);
ALTER TABLE SN_GUIAS_DETALLE_ESTADO ADD CONSTRAINT CK_SN_GUIAS_DET_EST CHECK (ESTADO_ENTREGA IN ('PENDIENTE', 'ENTREGADO', 'NO_ENTREGADO', 'ENTREGA_PARCIAL'));
ALTER TABLE SN_GUIAS_DETALLE_ESTADO ADD CONSTRAINT FK_SN_GUIAS_DET_EST_GUIA FOREIGN KEY (ID_GUIA) REFERENCES SN_GUIAS (ID) ON DELETE CASCADE;
ALTER TABLE SN_GUIAS_DETALLE_ESTADO ADD CONSTRAINT FK_SN_GUIAS_DET_EST_KDX FOREIGN KEY (KARDEX_ID) REFERENCES KARDEX (KARDEXID);

CREATE INDEX IDX_SN_GUIAS_DET_EST_GUIA ON SN_GUIAS_DETALLE_ESTADO (ID_GUIA);
CREATE INDEX IDX_SN_GUIAS_DET_EST_ESTADO ON SN_GUIAS_DETALLE_ESTADO (ESTADO_ENTREGA);

CREATE TABLE SN_GUIAS_DETALLE_CHAT (
    ID             INTEGER NOT NULL,
    ID_GUIA        INTEGER NOT NULL,
    KARDEX_ID      INTEGER NOT NULL,
    MENSAJE        VARCHAR(500) NOT NULL,
    FECHA_MENSAJE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO        VARCHAR(50) NOT NULL,
    TIPO           VARCHAR(15) DEFAULT 'CHAT' NOT NULL
);

ALTER TABLE SN_GUIAS_DETALLE_CHAT ADD CONSTRAINT PK_SN_GUIAS_DET_CHAT PRIMARY KEY (ID);
ALTER TABLE SN_GUIAS_DETALLE_CHAT ADD CONSTRAINT FK_SN_GUIAS_DET_CHAT_GUIA FOREIGN KEY (ID_GUIA) REFERENCES SN_GUIAS (ID) ON DELETE CASCADE;
ALTER TABLE SN_GUIAS_DETALLE_CHAT ADD CONSTRAINT FK_SN_GUIAS_DET_CHAT_KDX FOREIGN KEY (KARDEX_ID) REFERENCES KARDEX (KARDEXID);

CREATE INDEX IDX_SN_GUIAS_DET_CHAT_GUIA_KDX ON SN_GUIAS_DETALLE_CHAT (ID_GUIA, KARDEX_ID, FECHA_MENSAJE);
