/*
  Script: 04_create_estados_guias_y_vehiculo.sql
  Objetivo:
  - Catalogo configurable de estados de guias.
  - Migrar estado FINALIZADO -> ENTREGADO.
  - Habilitar vehiculo por placa en SN_GUIAS (ID_VEHICULO).
  Motor: Firebird 2.5

  Nota de compatibilidad:
  - Este script evita variables tipo :V_COUNT en EXECUTE BLOCK
    para no chocar con parsers que convierten ':' en parametros '?'.
*/

SET TERM ^ ;

/* 1) Tabla catalogo de estados */
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$RELATIONS
      WHERE RDB$RELATION_NAME = 'SN_GUIAS_ESTADOS_CFG'
  )) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE SN_GUIAS_ESTADOS_CFG (
          ID              INTEGER NOT NULL,
          CODIGO          VARCHAR(30) NOT NULL,
          NOMBRE          VARCHAR(60) NOT NULL,
          ACTIVO          CHAR(1) DEFAULT ''S'' NOT NULL,
          ORDEN_VISUAL    INTEGER DEFAULT 0,
          FECHA_CREACION  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
          FECHA_EDICION   TIMESTAMP,
          USUARIO_EDITA   VARCHAR(25)
      )
    ';
  END
END^

/* 2) Constraints e indices catalogo */
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$RELATION_CONSTRAINTS
      WHERE RDB$CONSTRAINT_NAME = 'PK_SN_GUIAS_ESTADOS_CFG'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE SN_GUIAS_ESTADOS_CFG ADD CONSTRAINT PK_SN_GUIAS_ESTADOS_CFG PRIMARY KEY (ID)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$RELATION_CONSTRAINTS
      WHERE RDB$CONSTRAINT_NAME = 'UQ_SN_GUIAS_ESTADOS_CFG_COD'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE SN_GUIAS_ESTADOS_CFG ADD CONSTRAINT UQ_SN_GUIAS_ESTADOS_CFG_COD UNIQUE (CODIGO)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$RELATION_CONSTRAINTS
      WHERE RDB$CONSTRAINT_NAME = 'CK_SN_GUIAS_ESTADOS_CFG_ACTIVO'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE SN_GUIAS_ESTADOS_CFG ADD CONSTRAINT CK_SN_GUIAS_ESTADOS_CFG_ACTIVO CHECK (ACTIVO IN (''S'', ''N''))';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$INDICES
      WHERE RDB$INDEX_NAME = 'IDX_SN_GUIAS_ESTADOS_CFG_ORD'
  )) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SN_GUIAS_ESTADOS_CFG_ORD ON SN_GUIAS_ESTADOS_CFG (ORDEN_VISUAL)';
END^

/* 3) Estados base */
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM SN_GUIAS_ESTADOS_CFG
      WHERE UPPER(TRIM(CODIGO)) = 'EN_ALISTAMIENTO'
  )) THEN
  BEGIN
    INSERT INTO SN_GUIAS_ESTADOS_CFG (ID, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL, FECHA_CREACION)
    VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM SN_GUIAS_ESTADOS_CFG), 'EN_ALISTAMIENTO', 'EN ALISTAMIENTO', 'S', 10, CURRENT_TIMESTAMP);
  END

  IF (NOT EXISTS(
      SELECT 1
      FROM SN_GUIAS_ESTADOS_CFG
      WHERE UPPER(TRIM(CODIGO)) = 'EN_RUTA'
  )) THEN
  BEGIN
    INSERT INTO SN_GUIAS_ESTADOS_CFG (ID, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL, FECHA_CREACION)
    VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM SN_GUIAS_ESTADOS_CFG), 'EN_RUTA', 'EN RUTA', 'S', 20, CURRENT_TIMESTAMP);
  END

  IF (NOT EXISTS(
      SELECT 1
      FROM SN_GUIAS_ESTADOS_CFG
      WHERE UPPER(TRIM(CODIGO)) = 'ENTREGADO'
  )) THEN
  BEGIN
    INSERT INTO SN_GUIAS_ESTADOS_CFG (ID, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL, FECHA_CREACION)
    VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM SN_GUIAS_ESTADOS_CFG), 'ENTREGADO', 'ENTREGADO', 'S', 30, CURRENT_TIMESTAMP);
  END
END^

/* 4) Campo vehiculo en guias */
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$RELATION_FIELDS
      WHERE RDB$RELATION_NAME = 'SN_GUIAS'
        AND RDB$FIELD_NAME = 'ID_VEHICULO'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE SN_GUIAS ADD ID_VEHICULO INTEGER';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$INDICES
      WHERE RDB$INDEX_NAME = 'IDX_SN_GUIAS_VEHICULO'
  )) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_SN_GUIAS_VEHICULO ON SN_GUIAS (ID_VEHICULO)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$RELATION_CONSTRAINTS
      WHERE RDB$CONSTRAINT_NAME = 'FK_SN_GUIAS_VEHICULO'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE SN_GUIAS ADD CONSTRAINT FK_SN_GUIAS_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO (VEHICULOID)';
END^

/* 5) Migracion FINALIZADO -> ENTREGADO */
UPDATE SN_GUIAS
SET ESTADO_ACTUAL = 'ENTREGADO'
WHERE UPPER(TRIM(COALESCE(ESTADO_ACTUAL, ''))) = 'FINALIZADO'^

UPDATE SN_GUIAS_ESTADOS
SET ESTADO = 'ENTREGADO'
WHERE UPPER(TRIM(COALESCE(ESTADO, ''))) = 'FINALIZADO'^

/* 6) Quitar checks fijos legacy */
EXECUTE BLOCK AS
BEGIN
  IF (EXISTS(
      SELECT 1
      FROM RDB$RELATION_CONSTRAINTS
      WHERE RDB$CONSTRAINT_NAME = 'CK_SN_GUIAS_ESTADO'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE SN_GUIAS DROP CONSTRAINT CK_SN_GUIAS_ESTADO';
END^

EXECUTE BLOCK AS
BEGIN
  IF (EXISTS(
      SELECT 1
      FROM RDB$RELATION_CONSTRAINTS
      WHERE RDB$CONSTRAINT_NAME = 'CK_SN_GUIAS_ESTADO_H'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE SN_GUIAS_ESTADOS DROP CONSTRAINT CK_SN_GUIAS_ESTADO_H';
END^

SET TERM ; ^

COMMIT;
