/*
  Script alterno sin EXECUTE BLOCK.
  Usar cuando la herramienta no soporta bloques anonimos (BindingCursor/IBO dataset).
  Ejecutar UNA SOLA VEZ sobre BD que aun no tenga estos objetos.
*/

CREATE TABLE SN_GUIAS_ESTADOS_CFG (
    ID              INTEGER NOT NULL,
    CODIGO          VARCHAR(30) NOT NULL,
    NOMBRE          VARCHAR(60) NOT NULL,
    ACTIVO          CHAR(1) DEFAULT 'S' NOT NULL,
    ORDEN_VISUAL    INTEGER DEFAULT 0,
    FECHA_CREACION  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_EDICION   TIMESTAMP,
    USUARIO_EDITA   VARCHAR(25)
);

ALTER TABLE SN_GUIAS_ESTADOS_CFG ADD CONSTRAINT PK_SN_GUIAS_ESTADOS_CFG PRIMARY KEY (ID);
ALTER TABLE SN_GUIAS_ESTADOS_CFG ADD CONSTRAINT UQ_SN_GUIAS_ESTADOS_CFG_COD UNIQUE (CODIGO);
ALTER TABLE SN_GUIAS_ESTADOS_CFG ADD CONSTRAINT CK_SN_GUIAS_ESTADOS_CFG_ACTIVO CHECK (ACTIVO IN ('S', 'N'));
CREATE INDEX IDX_SN_GUIAS_ESTADOS_CFG_ORD ON SN_GUIAS_ESTADOS_CFG (ORDEN_VISUAL);

INSERT INTO SN_GUIAS_ESTADOS_CFG (ID, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL, FECHA_CREACION)
VALUES (1, 'EN_ALISTAMIENTO', 'EN ALISTAMIENTO', 'S', 10, CURRENT_TIMESTAMP);

INSERT INTO SN_GUIAS_ESTADOS_CFG (ID, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL, FECHA_CREACION)
VALUES (2, 'EN_RUTA', 'EN RUTA', 'S', 20, CURRENT_TIMESTAMP);

INSERT INTO SN_GUIAS_ESTADOS_CFG (ID, CODIGO, NOMBRE, ACTIVO, ORDEN_VISUAL, FECHA_CREACION)
VALUES (3, 'ENTREGADO', 'ENTREGADO', 'S', 30, CURRENT_TIMESTAMP);

ALTER TABLE SN_GUIAS ADD ID_VEHICULO INTEGER;
CREATE INDEX IDX_SN_GUIAS_VEHICULO ON SN_GUIAS (ID_VEHICULO);
ALTER TABLE SN_GUIAS ADD CONSTRAINT FK_SN_GUIAS_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO (VEHICULOID);

UPDATE SN_GUIAS
SET ESTADO_ACTUAL = 'ENTREGADO'
WHERE UPPER(TRIM(COALESCE(ESTADO_ACTUAL, ''))) = 'FINALIZADO';

UPDATE SN_GUIAS_ESTADOS
SET ESTADO = 'ENTREGADO'
WHERE UPPER(TRIM(COALESCE(ESTADO, ''))) = 'FINALIZADO';

ALTER TABLE SN_GUIAS DROP CONSTRAINT CK_SN_GUIAS_ESTADO;
ALTER TABLE SN_GUIAS_ESTADOS DROP CONSTRAINT CK_SN_GUIAS_ESTADO_H;

COMMIT;

