/*
  Script: 05_create_retirados.sql
  Modulo: Retirados
  Motor : Firebird 2.5
  Nota  : Sin generators (ID por codigo MAX(ID)+1).
*/

CREATE TABLE SN_RETIROS_ESTADO (
    ID              INTEGER NOT NULL,
    KARDEX_ID       INTEGER NOT NULL,
    ESTADO          VARCHAR(20) NOT NULL,
    OBSERVACION     VARCHAR(200),
    FECHA_ESTADO    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO         VARCHAR(50) NOT NULL,
    FECHA_CREACION  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_EDICION   TIMESTAMP
);

ALTER TABLE SN_RETIROS_ESTADO ADD CONSTRAINT PK_SN_RETIROS_ESTADO PRIMARY KEY (ID);
ALTER TABLE SN_RETIROS_ESTADO ADD CONSTRAINT UQ_SN_RETIROS_ESTADO_KARDEX UNIQUE (KARDEX_ID);
ALTER TABLE SN_RETIROS_ESTADO ADD CONSTRAINT CK_SN_RETIROS_ESTADO_EST CHECK (ESTADO IN ('PARA_RETIRAR', 'RETIRADO'));
ALTER TABLE SN_RETIROS_ESTADO ADD CONSTRAINT FK_SN_RETIROS_ESTADO_KARDEX FOREIGN KEY (KARDEX_ID) REFERENCES KARDEX (KARDEXID);

CREATE INDEX IDX_SN_RETIROS_ESTADO_ESTADO ON SN_RETIROS_ESTADO (ESTADO);
CREATE INDEX IDX_SN_RETIROS_ESTADO_FECHA ON SN_RETIROS_ESTADO (FECHA_ESTADO);

