/*
  Script: 06_alter_kardex_geo.sql
  Modulo: Guias (Despachos) - POD GPS
  Motor : Firebird 2.5
*/

ALTER TABLE KARDEX ADD SN_LONGITUD NUMERIC(12,7);
ALTER TABLE KARDEX ADD SN_LATITUD NUMERIC(12,7);

CREATE INDEX IDX_KARDEX_SN_LONGITUD ON KARDEX (SN_LONGITUD);
CREATE INDEX IDX_KARDEX_SN_LATITUD ON KARDEX (SN_LATITUD);
